## 制御構文

### 条件分岐

#### if文

```powershell
if ($cond1) {
    echo "true1"
} elseif ($cond2) {
    echo "true2"
} else {
     echo "false"
}
```

#### TRUEと評価される値

```powershell
$true
1
'a'
"a"
```

#### FALSEと評価される値

```powershell
$false
0
""
```

#### switch文

```powershell
$v = 1
switch ($v) {
    1 { Write-Host "one" }
    2 { Write-Host "two" }
    Default { Write-Host "default" }
}
```

### ループ

#### ループ文

```powershell
for ($i = 0; $i -lt 4; $i++) {
    echo $i
}
```

```powershell
foreach ($i in @(1, 2, 3, 4)) {
    echo $i
}

foreach ($i in 0..4) {
    echo $i
}

$map = @{k1="v1"; k2="v2"; k3="v3"}
foreach ($i in $map) {
    echo $i
}

$list = New-Object System.Collections.ArrayList
$list.Add("i1")
$list.Add("i2") > $null
[void]$list.Add("i3")
foreach ($i in $list) {
    echo $i
}
```

```powershell
$i = 0
while ($i -lt 4) {
    echo $i
    $i++
}
```

```powershell
$i = 0
do {
    echo $i
    $i++
} while ($i -lt 4)
```

```powershell
$i = 0
do {
    echo $i
    $i++
} until ($i -gt 4-1)
```

いずれも

> 0
> 1
> 2
> 3

#### ループ制御文

```powershell
foreach ($i in 0..4) {
    if($i -eq 3){
        break
    }
    echo $i
}
```

> 1
> 2

```powershell
foreach ($i in 0..4) {
    if($i -eq 3){
        continue
    }
    echo $i
}
```

> 1
> 2
> 4

### 例外処理

#### try節

PowerShellのエラー「終了するエラー」「続行するエラー」のうち、デフォルトでCatchできるのは「終了するエラー」のみだが、$ErrorActionPreferenceに「Stop」を代入することで、両方例外としてCatchすることができるようになる。

| 定数             | 内容                                     |
| :--------------- | :--------------------------------------- |
| continue         | 例外は出力しつつ、処理も継続する(既定値) |
| silentlycontinue | 例外を出力せずに、処理を継続する         |
| stop             | 処理を終了する                           |

```powershell
$ErrorActionPreference = "Stop"

# 戻り値
$rc = 0

try{
    Write-Host "処理1を実行します。"
    Set-Content -Path ".\not_exist\not_exist.txt" -Value "test"
    Write-Host "処理2を実行します。"
}catch{
# }catch [Exception]{
    Write-Host "catch例外処理です。"
    Write-Host "Error:" $Error
    Write-Host "StackTrace:" $StackTrace
    $rc = 1
}finally{
    Write-Host "finally処理です。"
}

exit $rc
```

#### trap節

```powershell
# 例外発生時にスクリプトを停止する
trap [Exception] {
    write-host("ps_exception_2():trap")
    break
}

# 処理
```

```powershell
# 例外発生時もスクリプトを継続する
trap [Exception] {
    write-host("ps_exception_1():trap")
    continue
  }

# 処理
```
